menu:
  Home: /
  Archives: /Blog_Travel/archives/

widgets:
- search

cover:
  enable: true
  url: "https://lh5.googleusercontent.com/-9Lhb2BLpv48/R5DhuKt9zDI/AAAAAAAAOLw/Uk5tOEkHjBs/s0/IMG_1636.JPG"
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: false
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: 
rss:




social:
  github: 
  weibo: 
  google_plus: 

auto_change:
  enable: false
